name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.66.0
        with:
            components: clippy
      - uses: Swatinem/rust-cache@v2

      - run: cargo clippy -- -D warnings

  lint-rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          # We use nightly so that it correctly groups together imports
          toolchain: nightly
          components: rustfmt
      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt --check

  cargo-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Install Rust
          uses: dtolnay/rust-toolchain@1.66.0
        - uses: Swatinem/rust-cache@v2

        # Tests need a postgres installed
        - name: Install postgres
          run: sudo apt-get install postgresql postgresql-client
        - name: Update path
          run: find /usr/lib/postgresql/ -type d -name "bin" >> $GITHUB_PATH

        - run: cargo test
